# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Эл. Почта')),
                ('username', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Фимилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='api/avatars', verbose_name='Аватар')),
                ('tagline', models.CharField(blank=True, max_length=140, verbose_name='Статус')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетные записи',
                'ordering': ['username', 'email'],
                'permissions': (('user_account', 'can GET, POST, PUT, PATCH, DELETE'),),
                'db_table': 'Account',
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('username', 'email', 'created_at')]),
        ),
    ]
