# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='api/avatars/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
