# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('discription', models.TextField()),
                ('capture', models.ImageField(upload_to='category/%Y/%m/%d')),
            ],
            options={
                'db_table': 'Category',
                'verbose_name': 'Категория',
                'ordering': ['title'],
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('title', 'capture')]),
        ),
    ]
