# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('discription', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('capture', models.ImageField(upload_to='service/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'db_table': 'Service',
                'ordering': ['title'],
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('title', 'capture')]),
        ),
    ]
